### PR TITLE
Implement file searching

### PR DESCRIPTION
**Pull request by JBorrow**
Fixes simonsobs/librarian#29

### CODE REVIEW

**Comment by JBorrow** [comment]
TODO: CLI

**Comment by JBorrow** [comment]
CLI now done

**Comment by JBorrow** [comment]
@plaplant any thoughts on returning a 404 when we find no files v.s. just returning an empty list?

**Comment by plaplant** [comment]
@JBorrow is the idea that the only thing to change would be a different return code (i.e., 404 vs. 200), but otherwise the rest is similar? I'm open to that, as long as the webserver makes it clear that the issue is specifically that no files matched the query. For me personally I typically associate a 404 error with "unclear user error", which might not be the most useful result in this case.

**Pull request merged**
