### PR TITLE
Asyncify verification

### PR DESCRIPTION
**Pull request by JBorrow**
Uses asynchronous tasks in the verification pipeline to dispatch requests to remotes first, before moving on to our own problems.

### CODE REVIEW

**Comment by JBorrow** [comment]
Fixes #98

**Comment by JBorrow** [comment]
@kmharrington

**Comment by kmharrington** [comment]
I approve the general idea of this setup but have no idea how to review the code otherwise 👍

**Comment by JBorrow** [comment]
I will merge and test.

**Pull request merged**
